# Generated by Django 4.2.7 on 2025-10-04 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Habitat', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shape', models.CharField(choices=[('cylinder', 'Cylinder'), ('sphere', 'Sphere'), ('dome', 'Dome'), ('torus', 'Torus'), ('cube', 'Cube')], default='cylinder', max_length=20)),
                ('crew_size', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)])),
                ('mission_duration', models.IntegerField(default=30, help_text='Mission duration in days', validators=[django.core.validators.MinValueValidator(1)])),
                ('mission_type', models.CharField(choices=[('moon', 'Moon'), ('mars', 'Mars'), ('orbit', 'Orbit')], default='moon', max_length=20)),
                ('dimension_x', models.FloatField(default=10.0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('dimension_y', models.FloatField(default=10.0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('dimension_z', models.FloatField(default=10.0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('layout_data', models.JSONField(blank=True, default=dict, help_text='JSON data containing module positions and configurations')),
                ('total_volume', models.FloatField(default=0.0, help_text='Total habitat volume in cubic meters')),
                ('usable_space', models.FloatField(default=0.0, help_text='Usable space percentage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
